spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
spring.data.mongodb.uri=mongodb://localhost:27017/spring_security_mongo_db
spring.data.mongodb.auto-index-creation=true
server.port=8081
